### ISSUE TITLE
User Journey: See a schedule of upcoming lightning talks

### ISSUE THREAD

**Issue by mr-bagglesworth** [mr-bagglesworth/lightningTalks#1]
- [x] Public route showing upcoming lightning talks, soonest at top
- [x] Search by subject (autocomplete)
- [x] Search by speaker (autocomplete)
- [x] Search by tag(s) (which will be languages) - select multiple tags to narrow down the search. Another autocomplete function.
- [x] Organise by date and time (ascending / descending)
- [x] Allow me to see past lightning talks, as well as upcoming talks

**Comment by mr-bagglesworth** [comment]
### To do:
- make date sort and past talks buttons work together better
- check that date sort actually sorts by timestamp (and not entered order)
- add coursebook and gitter links (to users can identify clashes with other events)
- make future- proof tests for functions that use a timestamp
