### ISSUE TITLE
Date Sort and Past Talk buttons

### ISSUE THREAD

**Issue by mr-bagglesworth** [mr-bagglesworth/lightningTalks#17]
**Relates to #1**: schedule of upcoming lightning talks

### Acceptance Criteria:
- I want to clearly tell which tasks have past, and which are upcoming
- I want to be able to sort by date for both future and past talks

### Tasks:
- [x] implement buttons to sort talks by date, and show past talks
- [x] allow for sorting by date within history
- [x] check that date sort actually sorts by timestamp (and not entered order)
- [x] make future- proof tests for functions that use a timestamp

**Comment by martinbagshaw** [comment]
Addressed in [commit 51](https://github.com/mr-bagglesworth/lightningTalks/commit/a1f1ef65c47892c073f5900eb084a4c10b9c419a)
