### ISSUE TITLE
View potential clashes for a better booking experience

### ISSUE THREAD

**Issue by martinbagshaw** [mr-bagglesworth/lightningTalks#20]
### Acceptance Criteria:
- View other people's talk times and dates
- View course schedule
- View FAC Gitter

### Tasks:
- [ ] show in the talk booking form dates and times that are already booked up
- [ ] show a link to the Github coursebook, for people to check upcoming events
- [ ] show a link to the Gitter, to see if anything else is booked in
