### ISSUE TITLE
Bookmarks and Reminders

### ISSUE THREAD

**Issue by mr-bagglesworth** [mr-bagglesworth/lightningTalks#23]
### Acceptance Criteria
- See a list of bookmarked talks
- Possible push notification before talk

### Tasks:
- [ ] add checkbox to bookmark a talk (for logged in users)
- [ ] save bookmarked talks for user to database
- [ ] display bookmarked talks on dashboard screen
- [ ] look in to push notifications
